services:
  postgres:
    image: postgres:16-alpine
    container_name: notifyhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: notifyhub
      POSTGRES_USER: notifyhub
      POSTGRES_PASSWORD: notifyhub
    ports:
      - "5433:5432"
    volumes:
      - notifyhub_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notifyhub -d notifyhub"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notifyhub-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: notifyhub
      RABBITMQ_DEFAULT_PASS: notifyhub123
    volumes:
      - notifyhub_rabbitmqdata:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: notifyhub-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - notifyhub_redisdata:/data

volumes:
  notifyhub_pgdata:
  notifyhub_rabbitmqdata:
  notifyhub_redisdata: