server:
  port: 8080

spring:
  application:
    name: notifyhub

  datasource:
    url: jdbc:postgresql://localhost:5433/notifyhub
    username: notifyhub
    password: notifyhub
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 6b89d750448349
    password: 01c3cdad5ddc5555
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:notifyhub}
    password: ${RABBITMQ_PASSWORD:notifyhub123}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:dev-only-secret-CHANGE-ME-this-must-be-at-least-256-bits-long-for-HS256}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}